### ISSUE TITLE
Change default author (@rocketseat)

### ISSUE THREAD

**Issue by OfficialMarinho** [Rocketseat/gatsby-themes#20]
**Description of bug**
If I change the default author of the theme, he remains persistent in finding the author @rocketseat.

**To Reproduce**
1. Change the name '@rocketseat'
2. Configure ``gatsby-config.js`` to set the new author name
4. Open the preview

**Expected behavior**
Accept other author folder (name).

**Exception or Error**

``
Welcome, this is the default page of @rocketseat/gatsby-theme-docs from Rocketseat! To change this page just create a file named index.mdx inside @rocketseat/gatsby-theme-docs/text and place there your text. Also, if you need help, feel free to open an issue with a description of the problem you're facing or, if you prefer, you can chat with us on our Discord Community 👋🏻
``

**Environment:**
OS: Windows 10 (Gatsby running in Debian WSL)
Browser: Chrome 83.0.4103.116
Node v12.16.3

**Additional context**

**Comment by jpedroschmitz** [comment]
Hey @OfficialMarinho, the `siteAuthor` [is used for SEO reasons](https://github.com/Rocketseat/gatsby-themes/blob/master/%40rocketseat/gatsby-theme-docs/src/components/SEO.js#L86-L87) and is not related to folder names.

I believe you were expecting to change the folder name you shadow, but it is not possible. Since you’ve installed `@rocketseat/gatsby-theme-docs` and want to customize the `index.mdx`, you need to replace the theme’s original file `@rocketseat/gatsby-theme-docs/text/index.mdx`, with your own file to make any changes you need. You can't change the prefix `@rocketseat`, because this folder (and all its files) are included on the Webpack bundle.

**Comment by OfficialMarinho** [comment]
Ohhhh, that's sad. I don't knew about that.

Anyway, thanks for the answer. 👍
