### ISSUE TITLE
How can I show an image inline in mdx file?

### ISSUE THREAD

**Issue by fatihyildizhan** [Rocketseat/gatsby-themes#41]
I want to use default md image in mdx files. How can I achieve this?

I couldn't do with this tutorial: https://www.gatsbyjs.com/docs/working-with-images-in-markdown/

These are the dependencies:
```
 "dependencies": {
    "@rocketseat/gatsby-theme-docs": "^2.2.3",
    "gatsby": "^2.24.78",
    "gatsby-plugin-canonical-urls": "^2.3.13",
    "gatsby-plugin-google-analytics": "^2.3.18",
    "gatsby-plugin-manifest": "^2.4.34",
    "gatsby-plugin-offline": "^3.2.32",
    "gatsby-plugin-sharp": "^2.6.42",
    "gatsby-plugin-sitemap": "^2.4.17",
    "gatsby-remark-images": "^3.3.34",
    "gatsby-source-filesystem": "^2.3.34",
    "gatsby-transformer-remark": "^2.8.40",
    "prop-types": "^15.7.2",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  }
```

**Comment by jpedroschmitz** [comment]
Hey @fatihyildizhan, have you tried `![image caption](./image.png)`?

**Comment by fatihyildizhan** [comment]
@jpedroschmitz Which folder should I put the image?

**Comment by jpedroschmitz** [comment]
You can put either on your docs folder and reference as I did on my last comment or, if you prefer, just add the image on your static folder and reference like `![image caption](/image.png)`.

**Comment by jarredkenny** [comment]
Sorry to reopen, however the solution described above does not seem to work when a `basePath` is used in `gatsby-config.js`.

The site and all links between pages include the basePath, however images embedded using `![](./relative-image-name.svg)` end up linking to `/somehash/relative-image-name.svg` instead of the correct `bathpath/somehash/relative-image-name.svg`.
